### ISSUE TITLE
Coverage threshold error

### ISSUE THREAD

**Issue by andrew-cunliffe** [pocesar/grunt-mocha-istanbul#19]
Hi, I have been using this recently as a nice way to run my tests and its great except I'm a bit of a git and set my coverage requirements to 100% which is fine however whenever it drops below it causes a crash of grunt with the following output...  

```
.............../node_modules/istanbul/lib/cli.js:30
        throw ex; // turn it into an uncaught exception
              ^
ERROR: Coverage for statements (98.69%) does not meet threshold (100%)
ERROR: Coverage for branches (97.44%) does not meet threshold (100%)
ERROR: Coverage for lines (98.69%) does not meet threshold (100%)
ERROR: Coverage for functions (97.22%) does not meet threshold (100%)
Warning:  Use --force to continue.
```

Although I can fix coverage back to 100% this is a bit of a pain and I don't want to drop this threshold and allow a potential quality drop :) I also note this is thrown up from istanbul/cli.js however hope perhaps it can be caught by your wrapper module to protect you until the base problem can be resolved and if it breaks again you are protected here.

Many Thanks

**Comment by pocesar** [comment]
Closing this for now, if needed reopen
