### ISSUE TITLE
Include multiple paths

### ISSUE THREAD

**Issue by bblack** [pocesar/grunt-mocha-istanbul#21]
While we can `exclude` multiple paths, we can't include multiple paths since the `root` option is only a single path. Would like to be able to include multiple paths.

**Comment by pocesar** [comment]
Closing this for now, if needed reopen

**Comment by redBaronNc** [comment]
Hello, I have a question regarding combining tasks result into one report and I think it is linked to the question here,
You describe a task for ./app and ./lib in your example, how would you get a report combining the results from several task like this?

I see in the standard example you use the coverageFolder attribute  like so:

istanbul_check_coverage: {
          default: {
            options: {
              coverageFolder: 'coverage*', // will check both coverage folders and merge the coverage results
              check: {
                lines: 80,
                statements: 80
              }
            }
          }
        }

but this doesn't output a new folder with the combined report.
Is there a way to do this?
