### ISSUE TITLE
--harmony option

### ISSUE THREAD

**Issue by DylanPiercey** [pocesar/grunt-mocha-istanbul#25]
Where could one pass in the --harmony node option? It does not seem to work when passing it in through `options.mochaOptions`.

**Comment by kevinludwig** [comment]
+1 
What is the expected way to enable harmony when running mocha tests? It's not documented on your README, and I briefly checked your source code which has a top level option "harmony", that doesn't seem to work either. Is this not supported?

**Comment by pocesar** [comment]
everything that isn't "available" in the lib options, can be set using either mochaOptions or istanbulOptions

**Comment by pocesar** [comment]
I've updated the README for clarity. mochaOptions is an array of strings, so should be `mochaOptions: ['--harmony']`
