### ISSUE TITLE
Does this work with a mocha html test runner?

### ISSUE THREAD

**Issue by kmudrick** [pocesar/grunt-mocha-istanbul#26]

**Comment by pocesar** [comment]
Well, actually I'm not sure, because it uses istanbul cover and mocha command line executables, so it won't catch anything that is ran inside a browser.

**Comment by tomasAlabes** [comment]
Is this going to be part of the plugin someday or is not in the roadmap?
Thanks

**Comment by pocesar** [comment]
this would requiring using both libraries programatically inside the task instead of relying on the command line, I guess would make it less flexible and more error prone

**Comment by pocesar** [comment]
this would require another version of the task, using PhantomJS. I recomend using Karma for browser testing and coverage reports, which can generate coverage report just fine
