### ISSUE TITLE
Done callback never called in certain situations

### ISSUE THREAD

**Issue by petuomin** [pocesar/grunt-mocha-istanbul#32]
On lines 288-291:

```javascript
grunt.event.emit('coverage', coverage, function (d) {
  grunt.log.ok(result || 'Done. Check coverage folder.'); 
  done(d);
});
```

The module emits a coverage event with coverage data and a callback. If there are no listeners executing that callback, done will never be called.

**Comment by pocesar** [comment]
yup, that's by design. if you set `coverage: true` in your options, you must provide a `grunt.event.on('coverage', ...` as stated in the README https://github.com/pocesar/grunt-mocha-istanbul#boolean-optionscoverage-default-false

**Comment by petuomin** [comment]
Oops. Indeed. :)

Thanks for the quick reply.
