### ISSUE TITLE
Integration to coveralls doesn't work.

### ISSUE THREAD

**Issue by henricavalcante** [pocesar/grunt-mocha-istanbul#34]
I'm trying to integrate with coveralls.io but without success using this code on my grunt:

```
grunt.event.on('coverage', function(lcov, done){
    require('coveralls').handleInput(lcov, function(err){
        if (err) {
            return done(err);
        }
        done();
    });
});
```

and my coveralls.io status still unknown, you can check them out at https://coveralls.io/r/maisquestoes/api

**Comment by pocesar** [comment]
can you please execute it using `grunt travis --verbose`? I'm not able to tell what's wrong with it looking at the sources, since travis is succeeding

**Comment by henricavalcante** [comment]
https://travis-ci.org/maisquestoes/api/jobs/64909206

with --verbose

I've removed and added a repository again on coveralls.io but the problem still there.

**Comment by pocesar** [comment]
can you remove the `check` part of the options?

**Comment by henricavalcante** [comment]
It's ok now, thanks.

**Comment by pocesar** [comment]
it seems to be a bug then, it should execute the event if the check passes, I'm going to reopen it until I fix

**Comment by henricavalcante** [comment]
I think it's a Coveralls bug, because I put the check options back and there are no problem.

**Comment by pocesar** [comment]
alright, good to know :+1:

**Comment by henricavalcante** [comment]
Thanks for all =)
