### ISSUE TITLE
Require function

### ISSUE THREAD

**Issue by fpayer** [pocesar/grunt-mocha-istanbul#35]
Is it possible to require a function in the same way the grunt-mocha-test allows? When I try to do that, I get a "Cannot find module" error.

**Comment by pocesar** [comment]
not in the current state of the library. it uses command lines, grunt-mocha-test use mocha programatically

**Comment by fpayer** [comment]
So the makeshift solution is to just make a small js file to execute the function?

**Comment by pocesar** [comment]
yeah, that would suffice
