### ISSUE TITLE
combining coverage reports from multiple tasks?

### ISSUE THREAD

**Issue by redBaronNc** [pocesar/grunt-mocha-istanbul#39]
Hello,
Is it possible to combine the generated coverage reports from multiple tasks into one report?
I want to test different folder in my application and only take those folders into account for the coverage. It would be great to combine the generated reports into one report afterwards but I can't figure out if grunt-mocha-istanbul supports this.
I specially don't get what this means :     coverageFolder : covergage*

**Comment by pocesar** [comment]
the `istanbul report` command is what is needed for this to happen. 

according to https://github.com/gotwarlost/istanbul/issues/97#issuecomment-25222169

It won't happen automatically using this module, because it's focused more on the testing side than on the reporting side
