### ISSUE TITLE
Task name should be camelCase

### ISSUE THREAD

**Issue by fvanwijk** [pocesar/grunt-mocha-istanbul#42]
All grunt tasks that I have seen are in camel case. My JSCS checker is also complaining about `mocha_istanbul` being camel case, since the task name is an object key in the Gruntfile configuration.
Could you please rename the task?

**Comment by pocesar** [comment]
that would break everything for everyone. the cost benefit of this change is null, sorry

**Comment by fvanwijk** [comment]
I understand. I didn't see that you are already on 3.x. When 4.x may come out, you could reconsider renaming the task. For now you could consider making an alias.

In the meanwhile I use this workaround:

```javascript
grunt.task.renameTask('mocha_istanbul', 'mochaIstanbul');
```

Also see stephenharris/grunt-checktextdomain#2

**Comment by pocesar** [comment]
yeah, aliasing should do.
