### ISSUE TITLE
Support for check-coverage with isparta

### ISSUE THREAD

**Issue by xjamundx** [pocesar/grunt-mocha-istanbul#45]
`isparta` which I seem to need to support my es6 stuff doesn't provide the `check-coverage` function that comes with `istanbul` and therefore when I add coverage numbers into the config `grunt-mocha-istanbul` will fail.

Would it be possible to add a separate option to configure the coverage comand or default to istanbul inside of the `executeCheck` function?

**Comment by pocesar** [comment]
I'll close this for now, if isparta ever implements this, should work out of the box if it follows the same command line
