### ISSUE TITLE
How to make "grunt dev" to excecute, before all tests, the file "test/boostrap.test.js"?

### ISSUE THREAD

**Issue by jfmcode** [pocesar/grunt-mocha-istanbul#46]
So, I have added __grunt-mocha-istanbul__ as explained in https://blog.sergiocruz.me/unit-test-sailsjs-with-mocha-and-instanbul-for-code-coverage/

However, I do not known how to indicate that, before running the test, the file `test/boostrap.test.js` (created as indicated in http://sailsjs.org/documentation/concepts/testing) must be executed.

**Comment by pocesar** [comment]
you can do using `require: ['test/bootstrap.test.js']` in your options

**Comment by jfmcode** [comment]
Thanks!
