### ISSUE TITLE
Unable to run istanbul/mocha on code containing ES6 destructuring assignment

### ISSUE THREAD

**Issue by eugeneiiim** [pocesar/grunt-mocha-istanbul#48]
I'm trying to run mocha/istanbul on code containing [ES6 destructuring assignment](http://es6-features.org/#ObjectMatchingShorthandNotation). Node's `--harmony` flag does not enable destructuring assignment; it can only be enabled via `--harmony_destructuring`.

**Comment by pocesar** [comment]
so basically it needs a `nodeOptions` to pass to the process before istanbul and mocha, correct?

**Comment by eugeneiiim** [comment]
Yep, I started working on that here: https://github.com/blendlabs/grunt-mocha-istanbul/commits/em/nodeOptions

**Comment by pocesar** [comment]
implemented in 5.0.0, you can use babel with their plugins as well
