### ISSUE TITLE
Not able control coverage output folder path

### ISSUE THREAD

**Issue by jithin1987** [pocesar/grunt-mocha-istanbul#50]
How can I output coverage folder to a different path other than current folder ?. Specifying `coverageFolder` always bases it on current folder. So if I have 
```
coverageFolder: '/home/xyz/code/artifacts/coverage'
```

and if I invoke `grunt` at `/home/xyz/code`. Coverage gets written to `/home/xyz/code/home/xyz/code/artifacts/coverage`

**Comment by pocesar** [comment]
yeah, it's usual (and expected) from a grunt plugin perspective to use the current folder where `Gruntfile.js` is.

**Comment by pocesar** [comment]
@jithin1987 I've made the addition to being able to pass the cwd to the node process, see if this fixes it for you

https://github.com/pocesar/grunt-mocha-istanbul/tree/issue%2349 (`options.cwd`)
