### ISSUE TITLE
Dependencies in JavaScript files results in error during coverage collection

### ISSUE THREAD

**Issue by dominik0711** [pocesar/grunt-mocha-istanbul#52]
Hi. We have JavaScript files (ES5 style) which have dependencies to other objects in other JavaScript files like this:

    'use strict';

    var xx = xx || { };

    var testObj = xx.settings.getURL();

We receive the following error:

**TypeError: Cannot call method 'getURL' of undefined
    at namespace (/Users/<user>/src/js/auth.js:64:28)
    at Object.<anonymous> (/Users/<user>/js/auth.js:1485:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/<user>/Projects/ArtificialUnit/arcwork/build/node_modules/istanbul/lib/hook.js:109:37)**

**xx.settings** is another module that exports functions like this:

    'use strict';

    var xx = xx || { };

    // ****************************************************************************
    // Module: settings
    // ****************************************************************************

    xx.settings = (function namespace () {

        function getURL () {
          return 'http://test.local';
        }

       return {
         getURL: getURL
       };
     }());

What do we have to do to solve this problem? Where do we have to maintain the dependencies between the JavaScript files? Our **index.html** does already have all the dependencies defined!

This is our `grunt configuration`

    mocha_istanbul: {
       coverage: {
        src: '<%= path.source %>/js', // a folder works nicely
        options: {
          //mask: '*.spec.js'
        }
      },
    ...
    }

**Comment by pocesar** [comment]
you may try to require the files in mocha using:

```js
mocha_istanbul: {
   coverage: {
    src: '<%= path.source %>/js', // a folder works nicely
    options: {
       require:['path/to/xx.settings.js'],
      //mask: '*.spec.js'
    }
  },
...
}
```
