### ISSUE TITLE
add support for grunt 1.0.0

### ISSUE THREAD

**Issue by sagiegurari** [pocesar/grunt-mocha-istanbul#54]
since the peer dependency is of 0.4.x, new grunt version (1.x.x) is not supported.
Can you please update the needed?

**Comment by pocesar** [comment]
will do

**Comment by sagiegurari** [comment]
Thanks

**Comment by sagiegurari** [comment]
thanks a lot :+1:

**Comment by voxpelli** [comment]
@pocesar Grunt itself recommends a `"grunt": ">=0.4.0"` dependency rather than the `^1.0.0` that's now added http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released#peer-dependencies, so perhaps might to set that instead

**Comment by pocesar** [comment]
oh ok, thought grunt 1.x was a must-have upgrade
