### ISSUE TITLE
process args are overwritten

### ISSUE THREAD

**Issue by kahluagenie** [pocesar/grunt-mocha-istanbul#55]
I was trying to run grunt with some command line arguments and realized they disappear by the time my tests get invoked. Looking at the code, I see `var args = []` where I would expect it to be something along the lines of `var args = process.argv || []`

Is that behavior intentional? 
Cheers!

**Comment by pocesar** [comment]
yes, the args for the process spawning are created internally with no regards from external arguments from the command line. The arguments are passed using grunt options instead of the command line (so the task is 'portable', it will always work the same expected way every time)

**Comment by kahluagenie** [comment]
Ah cool, that makes total sense. I'm improving an existing build system, so I need to support command line args. Looks like I'll need to use mochaOptions. @pocesar thanks for the explanation!

**Comment by kahluagenie** [comment]
@pocesar one more question. Are you planning to release nodeOptions as a stable feature? That would be fantastic. I remember having problems shrinkwrapping packages when pointing to github for dependencies.

**Comment by kahluagenie** [comment]
Never mind, I made it work with mochaOptions. Had some confusion about how node flags work in general. Good talk, good talk :)

**Comment by pocesar** [comment]
@kahluagenie yes I do, I was expecting some feedback from people on issue #49 before merging to master and releasing it. I could put some additional info on the docs about the order of the flags (node > istanbul > mocha)
