### ISSUE TITLE
v5 breaks Mocha's --require option

### ISSUE THREAD

**Issue by nwoltman** [pocesar/grunt-mocha-istanbul#57]
Mocha's `--require` option is used to load modules, meaning both local files and modules in `node_modules`. The changes in fd4b0c53ab261a8ba0a3d5d1ce9f8bb1972f5f30 break this functionality because [this line](https://github.com/pocesar/grunt-mocha-istanbul/blob/master/tasks/index.js#L256) only allows local files to be `require`d (since `grunt.file.expand` only looks for local files using a glob).

**Comment by pocesar** [comment]
alright, it was implemented because of #47, I'll try to resolve the path before trying to expand it. i'll release 5.0.1 shortly
