### ISSUE TITLE
Untested files in test coverage report

### ISSUE THREAD

**Issue by dhruvmishra** [pocesar/grunt-mocha-istanbul#59]
I am not sure if this is already being answered here but I need help.

I am trying to include the files for which no tests exist in coverage report.

I see that "--include-all-sources" does that for istanbul https://github.com/gotwarlost/istanbul/blob/ad8ab1d7a5284407efb83d0d7a8b32eb6fbd93c4/lib/command/common/run-with-cover.js#L38

Is it possible to suggest if grunt-mocha-istanbul has something where I can get uncovered files in the coverage report?

Thanks!

**Comment by dhruvmishra** [comment]
I was able to figure it out, so closing the issue.

**Comment by pocesar** [comment]
just making sure if other people want the solution, add `['--include-all-sources']` to `istanbulOptions`
